server:
  port: 8888

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms_route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms_route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: sms_route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums_route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms_route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**

