#server:
#  port: 8083
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 231014
#    url: jdbc:mysql://192.168.139.128:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  redis:
#    host: 192.168.139.128
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#  mapper-locations: classpath:mapper/wms/*.xml
